CLASSES = [
    "background",
    "license plate"
]

MAX_OBJECTS_PER_IMAGE = 5

POSITIVE_ANCHOR_THRESHOLD = 0.7
NEGATIVE_ANCHOR_THRESHOLD = 0.3
MAX_ANCHORS = 50

TRAIN_PRE_NMS_TOP_N_PER_IMAGE = 2000
TEST_PRE_NMS_TOP_N_PER_IMAGE = 1000

TRAIN_POST_NMS_TOP_N_PER_IMAGE = 800
TEST_POST_NMS_TOP_N_PER_IMAGE = 300

POSITIVE_ROI_THRESHOLD = 0.5
MAX_ROIS = 100
POSITIVE_ROIS_RATIO = 1/4

IMAGE_SIZE = (640, 640)
ANCHOR_SCALES = [50, 50, 50, 50, 50]
ANCHOR_RATIOS = [(2, 1), (2.5, 1), (3, 1)]

ROIS_SHAPE = (7, 7)
FPN_NUM_CHANNELS = 256

TOP_N_MASK_PROPOSALS = 100
MASK_ROIS_SHAPE = (14, 14)
MASK_SHAPE = (28, 28)
MASK_THRESHOLD = 0.5

TEST_NMS_IOU_THRESHOLD = 0.3
TEST_CLASSIFICATION_SCORE_THRESHOLD = 0.8
TEST_MAX_BOXES_PER_CLASS = 10

WEIGHTS_DIR = "aolp-ckpts"

TRAIN_LOSSES_FILE = "aolp-train-losses.txt"
VALID_LOSSES_FILE = "aolp-valid-losses.txt"
